### PR TITLE
refactor: inline svgs on homepage

### LINKED ISSUE #170: Inline logos on the homepage
The logos on the homepage should be inline SVGs rather than external files.

### PR DESCRIPTION
**Pull request by morajabi**
Fixes #170

Hooray! We're getting to a good point (perf-wise). I almost cut +50% of logos' size (used [this awesome GUI](https://jakearchibald.github.io/svgomg/)) and inlined them.

### CODE REVIEW

**Comment by mxstbr** [comment]
Dang, this is actually where screenshot testing would be helpful to make sure we're not regressing!

**Comment by morajabi** [comment]
@mxstbr That works the best for our codebase. Good job @philpl!

**Comment by morajabi** [comment]
What's wrong with this?

**Comment by philpl** [comment]
@morajabi nothing, had a small conflict; but I'm about to merge it :+1:

**Comment by morajabi** [comment]
The emojis before/after a merge are my style, don't tell me to don't do that. 😅 💛

**Comment by morajabi** [comment]
@philpl You started the oss engines today, if you still have time take a look at #158 too 😉

**Pull request merged**
