### PR TITLE
Add Known Issues section to docs/tooling/stylelint

### PR DESCRIPTION
**Pull request by emilgoldsmith**
Adding a known issue to the Stylelint Processor as discussed in https://github.com/styled-components/stylelint-processor-styled-components/issues/130

@chinesedfan do you agree that this is the correct message to display?

### CODE REVIEW

**Comment by emilgoldsmith** [comment]
Cool :). I'll just wait for @chinesedfan to look it over as he was the one that identified the problem, and then let's merge it in.

**Comment by emilgoldsmith** [comment]
@chinesedfan  Yeah no reason not to be clear! I'll update it now

**Comment by emilgoldsmith** [comment]
@chinesedfan better?

@philpl if you could be so kind as to look over it again as my commit dismissed your review, thanks!

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Comment by chinesedfan** [comment]
@mxstbr You looks like a robot, haha! I am just a contributor of `stylelint-processor-styled-components`, which seems to not apply the same invitation policy. And of course, I know your words are send to @emilgoldsmith automatically.

**Comment by mxstbr** [comment]
Haha yeah that is a bot, see https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md#ownership

I wonder why Aeryn doesn't check membership in other teams though before sending another invite, /cc @orta

**Comment by emilgoldsmith** [comment]
@chinesedfan I think it might also be because these guidelines are pretty new and when you last submitted a PR Aeryn wasn't enabled?

**Comment by chinesedfan** [comment]
@emilgoldsmith You're right. It is set up last month. I will try to trigger this interesting thing by a meaningful PR. 😆

**Comment by orta** [comment]
All our Aeryn instances have moved to Peril now, it can do real org checks instead of teams: https://github.com/Moya/Aeryn/pull/23

**Pull request merged**
