### PR TITLE
Add eslint , prettier and stylelint to repo

### LINKED ISSUE #63: Add eslint and prettier to repo
Yellow! 

I was thinking maybe adding eslint and prettier would be a good idea here since the website has a lot of components and things can get messy with different ways of writing code

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

### PR DESCRIPTION
**Pull request by SaraVieira**
- [x] Add stylelint
- [x] Add eslint
- [x] Add prettier
- [x] Add lint-staged

Closes #63 

@philpl Can you take a look at this when you have time ? 😄

### CODE REVIEW

**Comment by SaraVieira** [comment]
@philpl @mxstbr?

**Comment by philpl** [comment]
Oh wow! Sorry for not seeing this! My notifications must have played a trick on me :(((

I’ll review it this afternoon and add a travis.yml too

**Comment by SaraVieira** [comment]
No problem man! People have busy lifes 😛

I was only being a nag because I wanted to work on the users page with eslint and prettier installed 
☺️

**Comment by philpl** [comment]
@SaraVieira I've rebased and rerun the formatters and also upgraded the packages :+1: (seems that npm-run-all was missing and an eslint comment had to be added to `CaptureScroll` too)

Mind checking if everything looks fine there before I go merge it? https://github.com/styled-components/styled-components-website/pull/71

Btw there was some way to allow memebers of the repo to rebase and push to contributor branches directly? Hm 🤔 

cc @mxstbr: I think we should add @SaraVieira to the repo, since she's already contributed a lot and is planning to help us out with even more stuff. If you're alright with that, Sara :smile: Might make it easier for you to contribute :wink:

Thanks again!

**Pull request closed without merging**
