### PR TITLE
add now.json

### PR DESCRIPTION
**Pull request by probablyup**

### CODE REVIEW

**Comment by arunoda** [comment]
Hey, I work with the `Now + GitHub` integration.
Seems like something not correct with the setup.

Did you occur any errors in the installation process?
How did you start installation the GitHub app?

This should be a very simple error. I would love to fix it ASAP.
Thanks.

**Comment by probablyup** [comment]
I think it’s just a permissions thing. Max will need to reinstall the
GitHub app.

**Comment by mxstbr** [comment]
On it

**Comment by mxstbr** [comment]
I just reinstalled the now app for this repo

**Comment by mxstbr** [comment]
Let's see if this deploys!

**Comment by arunoda** [comment]
Thanks @mxstbr 
Now you need to do a new commit to make it deploy.

**Comment by probablyup** [comment]
I think we need to add the “name” to the JSON since in the dashboard the
deploy is called “styled-components-docs”

**Pull request merged**
