### PR TITLE
add showcase with screenshots

### PR DESCRIPTION
**Pull request by overra**
Sorry for the delay on #275, busy summer. I'm not sure if it's just my computer but the images seemed to load a little slow. If it's just the size or amount of images we could use something like [lqip](https://github.com/zouhir/lqip-loader) or some other loading technique.

### CODE REVIEW

**Comment by overra** [comment]
I like that idea. Because of the aspect ratio I think it'll probably look best if the thumbnails are along the bottom. Any preference for carousel components?

**Comment by mxstbr** [comment]
No preference, I've never had to use one haha!

**Comment by morajabi** [comment]
Nextjs.org uses a CSS animation if it helps

**Comment by overra** [comment]
Hey there! Just wanted to push what I have so far and let you know I'm still working on this when I have time. I've borrowed a lot from the next.js showcase. 

I still need to add the name and link to the sites, change the navigation to thumbnails along the bottom and generate svgs for each screenshot.

Sorry it's taking so long, busy summer!

**Comment by mxstbr** [comment]
We should also add casper.com since it's a really well built and known site built with styled-components!

**Comment by mxstbr** [comment]
And another one: https://airbnb.design/cereal/

**Comment by mxstbr** [comment]
Another one: https://swipelife.tinder.com

**Comment by mxstbr** [comment]
Another one: https://moleskinestudio.com/

**Comment by mxstbr** [comment]
casper.com

**Comment by imbhargav5** [comment]
fortnitemaster.com

**Comment by morajabi** [comment]
Just putting prisma.io graphqlconf.org here, @mxstbr decides on the final list :)

**Comment by mxstbr** [comment]
This is getting awesome! 😍 Two points:

- One more site to showcase: https://www.theplayerstribune.com
- What are we going to do on mobile?

**Comment by morajabi** [comment]
@mxstbr I've just implemented this year conf last week! It'll be like this for 1 year at least :) (and more beautiful once we have sponsors and I can show that section too) just to give information, your call as I said!

**Comment by mxstbr** [comment]
@overra any chance you could look at mobile compatibility? Other than that this is pretty much done and _amazing_, I really want to ship it!

**Comment by el1f** [comment]
@mxstbr mind to assign this one to me? :)

**Comment by mxstbr** [comment]
@el1f I don't think you can push to this PR, just fork off from this branch and start a new PR! 👍

**Comment by mxstbr** [comment]
I have assigned you anyway :wink:

**Pull request closed without merging**
