### PR TITLE
Resized homely showcase thumbnail

### PR DESCRIPTION
**Pull request by Morganjackson**

### CODE REVIEW

**Comment by probablyup** [comment]
@Morganjackson this is 150kb larger than the original, can you run it through a lossless shrinker?

**Comment by el1f** [comment]
Hey @Morganjackson, can you please update your PR with this source? It's about 51% lighter and it should allow us to close this PR right after that :)

homely com au

**Comment by Morganjackson** [comment]
@el1f sorry for the delay should be good to go now!

**Review by el1f — APPROVED** [review]
While it's still slightly bigger than the original it is by a very small margin so I'll go ahead and approve it. Thanks for your help @Morganjackson!

**Pull request merged**
