### PR TITLE
Remove concepts link and rename try it to Homepage.

### PR DESCRIPTION
**Pull request by ZackTaylor**
Resolve issue #115

### CODE REVIEW

**Comment by philpl** [comment]
cc @mxstbr

**Comment by mxstbr** [comment]
Oh wait, gotta upgrade those Jest snapshots otherwise CI will keep failing!

**Comment by morajabi** [comment]
I see [most](https://webpack.js.org/guides/) [library](https://babeljs.io/docs/setup/) [sites](https://reactjs.org/tutorial/tutorial.html#an-interactive-component) just use the logo as a link to home page. Since we have kinda the lack of links 😆, we can put it there for now. It's just what I think, feel free to ignore it :)

**Comment by philpl** [comment]
@morajabi oops, yea, you’re totally right 😂 we’ll fix it after the ecosystem page

**Comment by ZackTaylor** [comment]
Is there something I need to do to fix this?

**Comment by philpl** [comment]
@ZackTaylor you’ll just need to update the snapshots with “jest -u” and commit the changes

**Comment by morajabi** [comment]
@philpl @ZackTaylor `yarn jest -- -u` if you don't have Jest installed globally.

**Comment by ZackTaylor** [comment]
Ok I updated the snapshots and pushed again

**Comment by ZackTaylor** [comment]
I ran `npm run jest -- -u` but the tests are still failing

**Comment by mxstbr** [comment]
What on earth there's a bunch of changes that are totally unrelated, super weird @ZackTaylor—sorry about that!

If the latest push doesn't work can you try `rm -rf node_modules && yarn` before running tests again?

**Comment by ZackTaylor** [comment]
AHA that worked! awesome thanks for being so helpful y'all :clap:!

**Comment by mxstbr** [comment]
Thank you @ZackTaylor, excited to ship this! Sorry for the troubles that were unrelated to your PR :blush:

**Pull request merged**
