### PR TITLE
Fix typo in theming.md file

### PR DESCRIPTION
**Pull request by joe-orav**
#716

Changed "Overidden" to "Overridden" in the theming.md file

### CODE REVIEW

**Review by sk22 — CHANGES_REQUESTED** [review]
unintended code style change next to typo fix :/

**Comment by joe-orav** [comment]
> unintended code style change next to typo fix :/

Is this regarding the semi-colons? If so, the package.json file specifies a "--no-semi" option for prettier when commiting changes in .md files. I'm not able to override that unless that needs to be removed?

**Comment by sk22** [comment]
> > unintended code style change next to typo fix :/
> 
> Is this regarding the semi-colons? If so, the package.json file specifies a "--no-semi" option for prettier when commiting changes in .md files. I'm not able to override that unless that needs to be removed?

Oh huh, well then I guess it should be fine then

**Review by sk22 — APPROVED** [review]

**Comment by probablyup** [comment]
Fixed in #727

**Pull request closed without merging**
