### PR TITLE
Added React-GA for Google Analytics #91

### PR DESCRIPTION
**Pull request by harshmaur**

### CODE REVIEW

**Comment by mxstbr** [comment]
Yeah so the issue here is that `react-ga` can't be server-side rendered. You should be able to add a `if (window !== undefined)` clause before the `initGa` thing, ref: https://github.com/react-ga/react-ga/issues/98

That should fix it.

**Comment by harshmaur** [comment]
Cant get it to work :(

**Comment by philpl** [comment]
@mxstbr @harshmaur Have you tried it with `typeof window === 'object'` instead of comparison to `undefined` directly? Otherwise this will throw a referenceerror.

**Comment by mxstbr** [comment]
The test is still failing in `react-ga` though, not our code 😕

**Comment by philpl** [comment]
@mxstbr That's probably because the test runs in a browser-like environment (jsdom), but not in a real one. So the node is searching for probably doesn't exist there 😢

**Comment by mxstbr** [comment]
Yeah but that means it would also fail if it was server-side rendered.

**Comment by mxstbr** [comment]
Uhh, what just happened? I didn't close this at all, I was only trying to fix the test! 😭  Where did the branch go?!

**Comment by mxstbr** [comment]
I'm so sorry @harshmaur I just did something very weird, would you mind submitting that PR again? Super sorry

**Comment by harshmaur** [comment]
I dont know what just happened, it seems like a new PR got created with the changes you made, When I am trying to compare for the changes, I do not see any and I am not able to make a PR 🤔

**Comment by harshmaur** [comment]
I think you can reopen the PR?

**Comment by mxstbr** [comment]
I can't reopen it either, the button is greyed out. I have no clue what just happened! Can you push your changes again?

**Pull request closed without merging**
