### PR TITLE
Try out @styled-icons packages instead of single package

### PR DESCRIPTION
**Pull request by StevenLangbroek**
Brb ;)

### CODE REVIEW

**Comment by StevenLangbroek** [comment]
@el1f for some reason your fork doesn't show up when creating a PR, how do you want to proceed with this?

**Comment by el1f** [comment]
Seems like it applied the changes on `master` rather than on my fork. No big issue, let's go ahead and merge your PR to styled-components and close #604 as it doesn't make any more sense now :)
Thanks again for the support my friend :)

**Comment by StevenLangbroek** [comment]
No problem at all :) preferred to merge your branch since the credit is all yours. Great work <3

**Comment by mxstbr** [comment]
Amazing, finally!!! :tada: :tada: :tada:

**Pull request merged**
