### PR TITLE
New footer design implemented

### PR DESCRIPTION
**Pull request by tomvaneygen**
New footer design implemented as described in https://github.com/styled-components/styled-components-website/issues/157

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome! Do you have a screenshot of what it looks like now by any chance?

**Comment by philpl** [comment]
@tomvaneygen I’m pretty sure that you’ll unfortunately need to update the screenshot tests using “yarn integration -u”.

@mxstbr this will also show you the footer 😬

**Comment by tomvaneygen** [comment]
@mxstbr @philpl I added the screenshots

**Comment by philpl** [comment]
Looks like the fonts render differently on Windows (?) including the emojis. I’ll see if I can fix that soon. But since the tests pass this is alright!

Super work ⭐️

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Pull request merged**
