### PR TITLE
Update inline-code style

### PR DESCRIPTION
**Pull request by Jinksi**
#130 
Based upon Github `inline code` style.

### CODE REVIEW

**Comment by mxstbr** [comment]
Screenshot?

**Comment by Jinksi** [comment]
Screenshot:  
screen shot 2017-10-05 at 8 44 23 pm

**Comment by SaraVieira** [comment]
Deployed version: https://styled-components-docs-wbvnnwqfmx.now.sh

**Comment by SaraVieira** [comment]
@Jinksi You need to update the snapshots 😔

**Comment by mxstbr** [comment]
Hmm, looks better but I feel like the background thing doesn't work super well with our typography. The code font is so different from the normal font, do we even need the background? What does it look like with that removed?

**Comment by Jinksi** [comment]
screen shot 2017-10-05 at 8 51 16 pm

**Comment by SaraVieira** [comment]
what do you guys think of changing the font to https://fonts.google.com/specimen/Roboto+Mono ?

**Comment by mxstbr** [comment]
Operator Mono is kinda part of the styled-components identity, I'd hate to remove it.

**Comment by philpl** [comment]
@mxstbr We actually removed the background-box from inline code on purpose after a recommendation from Andrey

**Comment by SaraVieira** [comment]
I think just adding the spacing helped a lot :)

**Comment by SaraVieira** [comment]
@Jinksi One test is still failing 😔

**Comment by morajabi** [comment]
But this much of space and light font makes it like a separator.

**Comment by philpl** [comment]
Small nit, it's a little off centre (Chrome screenshot), and on iOS (not the screenshot) the baseline is a little off

screen shot 2017-10-05 at 12 58 09

The previous implementation we had put the text on the same baseline and used margin+padding (not just padding) to keep the background "floating" in the centre behind the text

**Comment by mxstbr** [comment]
I like it more without the backgroud color but the space on the side needs to be adapted to be the same as an actual space.

**Comment by Jinksi** [comment]
@SaraVieira Jest is throwing `SyntaxError: Unexpected token import` on `/test/components/Code.spec.js` when I run `yarn jest -u`. Any ideas? 😕

**Comment by Jinksi** [comment]
Increase font-size, remove background & vertically align:
screen shot 2017-10-06 at 6 49 36 am

**Comment by morajabi** [comment]
@Jinksi You need to run `yarn jest -- -u` to pass the `-u` arg down to the jest not yarn itself. Also, If it doesn't work either, try removing `node_modules` and reinstalling with `yarn`.

**Comment by Jinksi** [comment]
😅  Sorted it, some cache issue with jest. I cloned a fresh copy and snapshots updated ok.

**Comment by mxstbr** [comment]
Thanks @Jinksi!!

**Comment by Jinksi** [comment]
@mxstbr Cheers! ✌️

**Pull request merged**
