### PR TITLE
Add FAQ about duplicated module issue

### PR DESCRIPTION
**Pull request by gribnoysup**
A draft for two new sections in FAQ related to https://github.com/styled-components/styled-components/pull/1412

Deployed a preview: https://styled-components-docs-unjvprisxg.now.sh/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

I don't like section titles very much, I feel that they are too long. But I couldn't come up with better ones 😿

### CODE REVIEW

**Comment by gribnoysup** [comment]
Do you still want this to be in the FAQ? @mxstbr @philpl

**Comment by gribnoysup** [comment]
Oh, didn't want to rush you, sorry 😊 Can you create a short URL for https://github.com/styled-components/styled-components/pull/1412 so we can finish it also? I can do it myself, but having this URL in some service can provide you with good insights, for example how often people are encountering this issue

**Comment by mxstbr** [comment]
Working on it! Will register `s-c.sh` and use that as a custom domain for `bit.ly`. Which specific link do you want shortened? `https://styled-components-docs-unjvprisxg.now.sh/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library`?

**Comment by mxstbr** [comment]
Oh I guess `/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page` makes even more sense, going to shorten that!

**Comment by gribnoysup** [comment]
Was about to suggest exactly that! Thank you so much 👍

**Pull request merged**
