### PR TITLE
changed installation instructions

### PR DESCRIPTION
**Pull request by ranidu-harshana**

### CODE REVIEW

**Comment by probablyup** [comment]
The longform syntax is intentional because it’s more obvious, but it does seem like the save switch can be dropped

**Comment by ranidu-harshana** [comment]
> The longform syntax is intentional because it’s more obvious, but it does seem like the save switch can be dropped

ok. may I do it or close it

**Comment by probablyup** [comment]
@ranidu-harshana if you could just put `i` back to `install` then that would be good thanks

**Comment by ranidu-harshana** [comment]
@probablyup Done

**Review by probablyup — APPROVED** [review]
Thanks!

**Pull request merged**
