### PR TITLE
Upgrade to next v7

### PR DESCRIPTION
**Pull request by mxstbr**
This is based on #300, so until that's merged you'll also see those changes in this branch.

### CODE REVIEW

**Comment by probablyup** [comment]
Let's hold off. There's no real win to updating to alpha software

**Comment by mxstbr** [comment]
@timneutkens made me do it

**Comment by timneutkens** [comment]
```
    {	
      "path": ".next/bundles/pages/**/*.js",	
      "maxSize": "50kB"	
    },
```

This should probably be changed to:

```
    {	
      "path": ".next/static/*/pages/**/*.js",	
      "maxSize": "50kB"	
    },
```

**Comment by timneutkens** [comment]
🎉 💯

**Pull request merged**
