### PR TITLE
Add eslint, prettier and stylelint to repo

### PR DESCRIPTION
**Pull request by philpl**
- Also add .travis.yml

Rebased & Updated branch of: https://github.com/styled-components/styled-components-website/pull/65

cc @SaraVieira

### CODE REVIEW

**Comment by SaraVieira** [comment]
@philpl It seems like the tests are failing :/

**Comment by philpl** [comment]
@SaraVieira Fixed! Seems it was caused by faulty filenames in the test (case sensitivity)

**Comment by SaraVieira** [comment]
@philpl Oh god that error , I have been through that so many times It hurts :(

**Comment by philpl** [comment]
ok! AWESOME! done! Thanks again :smile:

**Comment by mxstbr** [comment]
YES this is great, thanks!

**Pull request merged**
