### PR TITLE
Update name in now.json

### PR DESCRIPTION
**Pull request by mxstbr**

### CODE REVIEW

**Comment by mxstbr** [comment]
```
Module build failed: ReferenceError: Unknown plugin "module-resolver" specified in "/home/nowuser/src/.babelrc" at 1, attempted to resolve relative to "/home/nowuser/src"
07/04 06:26 PM (1h)
    at /home/nowuser/src/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
07/04 06:26 PM (1h)
    at Array.map (<anonymous>)
07/04 06:26 PM (1h)
    at Function.normalisePlugins (/home/nowuser/src/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
07/04 06:26 PM (1h)
    at OptionManager.mergeOptions (/home/nowuser/src/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
07/04 06:26 PM (1h)
    at OptionManager.init (/home/nowuser/src/node_modules/next/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
07/04 06:26 PM (1h)
    at File.initOptions (/home/nowuser/src/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:212:65)
07/04 06:26 PM (1h)
    at new File (/home/nowuser/src/node_modules/next/node_modules/babel-core/lib/transformation/file/index.js:135:24)
07/04 06:26 PM (1h)
    at Pipeline.transform (/home/nowuser/src/node_modules/next/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
07/04 06:26 PM (1h)
    at transpile (/home/nowuser/src/node_modules/next/node_modules/babel-loader/lib/index.js:48:20)
07/04 06:26 PM (1h)
    at /home/nowuser/src/node_modules/next/node_modules/babel-loader/lib/fs-cache.js:118:18
07/04 06:26 PM (1h)
 @ multi ./~/next/dist/client/next.js ./utils/offline.js ./utils/track.js
07/04 06:26 PM (1h)
    at /home/nowuser/src/node_modules/next/dist/server/build/index.js:182:21
07/04 06:26 PM (1h)
    at /home/nowuser/src/node_modules/webpack/lib/Compiler.js:272:15
07/04 06:26 PM (1h)
    at Compiler.emitRecords (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:367:37)
07/04 06:26 PM (1h)
    at /home/nowuser/src/node_modules/webpack/lib/Compiler.js:265:12
07/04 06:26 PM (1h)
    at /home/nowuser/src/node_modules/webpack/lib/Compiler.js:360:11
07/04 06:26 PM (1h)
    at next (/home/nowuser/src/node_modules/tapable/lib/Tapable.js:218:11)
07/04 06:26 PM (1h)
    at Compiler.compiler.plugin (/home/nowuser/src/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
07/04 06:26 PM (1h)
    at next (/home/nowuser/src/node_modules/tapable/lib/Tapable.js:220:14)
07/04 06:26 PM (1h)
    at /home/nowuser/src/node_modules/sw-precache-webpack-plugin/lib/index.js:98:18
```

**Comment by mxstbr** [comment]
Not sure how to solve that error.

**Comment by probablyup** [comment]
@mxstbr it worked!!

**Comment by probablyup** [comment]
Ok so last thing to consider here... how do we clear cloudflare programmatically?

**Comment by probablyup** [comment]
I adjusted some CF settings... let's see if things work as I'm hoping.

**Pull request merged**
