### PR TITLE
Initial work to add algolia to app

### PR DESCRIPTION
**Pull request by imbhargav5**
I requested algolia docsearch for config to add it out app. If we have a design I will update the UI and snapshots to match the designs. We will track it all here.

### CODE REVIEW

**Comment by mxstbr** [comment]
The design from #158 looked pretty good, let's go with that?

**Comment by imbhargav5** [comment]
@mxstbr I see one image related to the design for the input. Do we have any images that I can look at for reference as to how the input will look like on different devices?

**Comment by probablyup** [comment]
@imbhargav5 I'd do the dropdown style for tablet (768) & up and then do a takeover style (full height & width with a close X) for 767 down

**Comment by imbhargav5** [comment]
Sounds good.

**Comment by imbhargav5** [comment]
@probablyup @mxstbr I am working on the mobile nav part right now. Do you have a screenshot/design for how the search would like on smaller screens? That would really help.

**Comment by mxstbr** [comment]
😍 

Probably just the same thing but full-screen on mobile?

**Comment by probablyup** [comment]
@imbhargav5 I was thinking something simple like this with a close "X" in the top right corner https://cdn.dribbble.com/users/186850/screenshots/4127824/reading_-_search_results.png

**Comment by imbhargav5** [comment]
@probablyup I see. This helps. 😀

**Comment by probablyup** [comment]
Can’t use css and a media query for the mobile look?

**Comment by imbhargav5** [comment]
I think it's doable only if I change the structure of the navbar and mobileNavbar elements. A bit more than just media queries I would say. Will update PR in today or tomorrow.

**Comment by imbhargav5** [comment]
So, inherently, the way Docsearch appends search results right beside the input is causing some layout issues but I made an ugly, very much work in progress modal for mobile. Please take a look and see if there are some issues that we can fix before I get into styling. @probablyup

**Comment by probablyup** [comment]
Some notes so far:

1. It'd be great if the hover coloring etc could be adjusted to better match our website color scheme

2. We should have the search always be visible and live outside that collapse area for mobile

**Comment by imbhargav5** [comment]
Ok. So for 2 should I put a search icon beside the collapse button?

**Comment by probablyup** [comment]
I would figure out how the collapse works and then just move that whole component out of the collapse zone so it goes to the left of the collapse chevron

**Comment by imbhargav5** [comment]
[Image from Gyazo](https://gyazo.com/2734ad5191397c026b114f724e9e8f19)

**Comment by imbhargav5** [comment]
Let's go!!

**Comment by sag1v** [comment]
@imbhargav5 That looks great!

**Pull request merged**
