### PR TITLE
Added alternative install instructions

### PR DESCRIPTION
**Pull request by JamesJefferyUK**
I've added the alternative installation instructions from the README. I've tightened it up a bit and made it more concise. I hope it's ok :)

Any problems let me know.

image

### CODE REVIEW

**Comment by JamesJefferyUK** [comment]
Does anyone know why the other commits are showing up too? I did this on a different branch. Is that because the other changes are not merged to master yet?

**Comment by mxstbr** [comment]
When you `git checkout -b other-branch` it takes the currents branch status and starts the new one based on that. You were probably on your logo branch when you did the `git checkout`, so it took that and made the new branch based on the logo branch.

The fix is to go to master, delete this branch locally (`git checkout master && git branch -D add-alt-install-instructions`), then start the branch anew from master (`git checkout -b add-alt-install-instructions`), cherry-pick your commit that added the alternative installation instructions (`git cherry-pick ce615fe`) and force push to your remote. (`git push origin add-alt-installation-instructions --force-with-lease`)

**Comment by JamesJefferyUK** [comment]
I see what I did. I merged the logo commit to master for some odd reason. Anyway, reverted to upstream master, created new branch and cherry picked. Will open new pull request in a moment. Sorry about that.

**Comment by JamesJefferyUK** [comment]
I see what I did. I merged the logo commit to master for some odd reason. Anyway, reverted to upstream master, created new branch and cherry picked. All done 👍  And thanks for the advice @mxstbr it was very helpful.

**Comment by mxstbr** [comment]
Awesome, looks great! Just gotta get those tests fixed, but I don't think they fail because of your code... :cry:

/cc @philpl

**Comment by JamesJefferyUK** [comment]
It looks like the image snapshot comparisons are failing. I did take a look to see how I can fix but still stumped.

**Comment by mxstbr** [comment]
No worries, it's not you, it's a dependency: https://twitter.com/_philpl/status/943159160966930434

We'll get that resolved!

**Comment by philpl** [comment]
@JamesJefferyUK There was an issue with a changed API in Puppeteer 0.13.0; We've fixed the integration tests, pinned the version and pushed a hotfix to master.

https://github.com/styled-components/styled-components-website/commit/c3e1499e58002103d3daf6d16375b6ac67bb1065

Can you please rebase your branch and run `yarn integration -u` to update the screenshots? This should fix the tests :wink:

**Comment by mxstbr** [comment]
```sh
# Get newest master changes
git checkout master
git pull origin master
# Go to this branch
git checkout add-alt-install-instructions
# Rebase on top of new changes
git rebase master
# Update tests
yarn run integration -u
```

**Comment by JamesJefferyUK** [comment]
I had to sync my forked repo, then rebase. I did this:

```
git fetch upstream
git checkout master
git merge upstream/master
git checkout add-alt-install-instructions
git rebase master
yarn run integration -u
```

I'm getting errors:

```
~/P/styled-components-website ❯❯❯ yarn run integration -u                                               [1h23m]
yarn run v1.3.2
$ next build
> Using external babel configuration
> location: "/Users/god/Projects/styled-components-website/.babelrc"
> Using "webpack" config function defined in next.config.js.
Total precache size is about 5.49 MB for 61 resources.
Webpack Bundle Analyzer saved stats file to /var/folders/ms/jcl_wlwd0ks8rq3y_vk6x8d80000gn/T/c544cad3-4e23-466e-aa00-74274eacb182/.next/stats.json
$ jest -c .jest-integration.config.js --forceExit --silent --runInBand -u
 FAIL  integration-test/pages.spec.js (30.559s)
  ● Pages › should match Homepage snapshot

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should match Basics snapshot

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render Advanced until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render API Reference until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render Tooling until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render FAQs until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Snapshot Summary
 › 2 snapshots updated in 1 test suite.

Test Suites: 1 failed, 1 total
Tests:       6 failed, 6 total
Snapshots:   2 updated, 2 total
Time:        30.68s, estimated 35s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/P/styled-components-website ❯❯❯ yarn run integration -u                                             [1h24m] M
yarn run v1.3.2
$ next build
> Using external babel configuration
> location: "/Users/god/Projects/styled-components-website/.babelrc"
> Using "webpack" config function defined in next.config.js.
Total precache size is about 5.49 MB for 61 resources.
Webpack Bundle Analyzer saved stats file to /var/folders/ms/jcl_wlwd0ks8rq3y_vk6x8d80000gn/T/06e72f9a-8ab7-4a55-bd72-561f156dd50c/.next/stats.json
$ jest -c .jest-integration.config.js --forceExit --silent --runInBand -u
 FAIL  integration-test/pages.spec.js (30.41s)
  ● Pages › should match Homepage snapshot

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should match Basics snapshot

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render Advanced until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render API Reference until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render Tooling until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  ● Pages › should render FAQs until the end of the docs page

    TypeError: page.setRequestInterception is not a function

      at _callee$ (integration-test/pages.spec.js:63:20)
      at tryCatch (node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/next/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/next/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Snapshot Summary
 › 2 snapshots updated in 1 test suite.

Test Suites: 1 failed, 1 total
Tests:       6 failed, 6 total
Snapshots:   2 updated, 2 total
Time:        30.528s, estimated 35s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by philpl** [comment]
@JamesJefferyUK You'll have to run `yarn` again so that `puppeteer` updates to `0.13.0` :smile:

**Comment by mxstbr** [comment]
Oh damn, I forgot about that, my bad! Yeah, run `yarn` again to get the updated dependencies.

**Comment by JamesJefferyUK** [comment]
All done. Passes now. I will do the same on the other pull request too.

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Pull request merged**
