### PR TITLE
[WIP] Add Navbar to homepage

### PR DESCRIPTION
**Pull request by mxstbr**
This is a WIP idea, /cc @morajabi. The idea is that the navbar background is transparent when the page is at the top, and it turns into it's normal pink once the user scrolls:

screen shot 2017-10-07 at 1 22 15 pm

screen shot 2017-10-07 at 1 26 20 pm

It's already fully mobile compat and just doesn't show the sidebar on the homepage. (I added a `showSideNav` prop)

> Note: We should probably enable that prop for the Ecosystem page until we get around to creating a more comprehensive, auto-generated SidebarNav?

This is WIP because even with debouncing scrolling is janky, and the transition needs to be reworked to use opacity rather than background to be smoother too. I don't have more time at the moment, so I'd be happy if somebody could take this branch and finish it off!

### CODE REVIEW

**Comment by morajabi** [comment]
Hmm actually @philpl and I have discussed it and we agreed to first refactor sidebar #131 for the Ecosystem page and then get to this. Anyway, it's not a big deal :)

**Comment by mxstbr** [comment]
That seems like more effort and I had a bit of time so I figured might as well get this done :wink:

**Comment by morajabi** [comment]
@mxstbr Great! So is background transition that bad? Also take a look at this https://github.com/brigade/react-waypoint

**Comment by morajabi** [comment]
Did you see the `react-waypoint`?

**Comment by morajabi** [comment]
The problem with the scroll event handler is, it's invoked when I stop scrolling.

**Comment by mxstbr** [comment]
Niceee, much better-thanks @morajabi!

WDYT @philpl?

**Comment by philpl** [comment]
Looks amazing! Let’s ship it 🦋

**Pull request merged**
