### PR TITLE
Fix video aspect ratio

### PR DESCRIPTION
**Pull request by ink8bit**
# Video from `motivation` page

Fixed an issue with a broken layout of the motivation video.

## Steps to reproduce
1. Go to https://www.styled-components.com/docs/basics#motivation
2. Switch to a mobile device in dev tools

### CODE REVIEW

**Comment by ink8bit** [comment]
> Just one tiny request, could we make it so it doesn't grow to full-width on desktop?

Of course we can! 

@mxstbr  Please, check this commit https://github.com/styled-components/styled-components-website/pull/142/commits/2d07f9ca6814485af389e3015efb7e14a339290b

**Comment by morajabi** [comment]
Shouldn't we use our `mobile` media helper? I think it's in `utils/media`. If it's a special media width, then there's no problem.

**Comment by ink8bit** [comment]
Added a `media` helper https://github.com/styled-components/styled-components-website/pull/142/commits/d4e91e93b527a9da09092be5a3d0083ae9cda000

But I guess that it is `phone`-helper.

**Comment by morajabi** [comment]
@ink8bit Right I hadn't seen that :) It's better now, Thanks!

**Pull request merged**
