### PR TITLE
Add Tooling Section 

### PR DESCRIPTION
**Pull request by MicheleBertoli**
Following the discussions #62 in and #64, this PR implements a "Tooling" sections.
It also moves the babel plugin page from "Advanced" to "Tooling".

### CODE REVIEW

**Comment by philpl** [comment]
Nice! I really like the idea of having a separate section for tooling! It opens up the possibility of adding a lot more utilities in the future :tada:

I’m working on a new branch that switches all sections over to be written in markdown instead. Do you think we should merge this first and incorporate your changes into it? I’m not quite sure which way around it’s going to be easier, as there’s some miscellaneous changes in both

https://github.com/styled-components/styled-components-website/pull/74

**Comment by mxstbr** [comment]
Yesss this is super awesome!!

We want to integrate the docs for the stylelint processor too, and all the Babel plugin docs, so that in the end a) more people will find the tooling and b) it's all in one place 👌

**Comment by philpl** [comment]
I'll go ahead and merge the section over at #77, which is this PR + the merged back changes :+1: :smile:

**Comment by MicheleBertoli** [comment]
Thank you very much @philpl @mxstbr

**Pull request closed without merging**
