### PR TITLE
Join showcase and users manifest into a single file

### PR DESCRIPTION
**Pull request by el1f**
Solves #533

### CODE REVIEW

**Comment by mxstbr** [comment]
Wait now there's no changes anymore? :scream: What did I do?!?!

**Comment by el1f** [comment]
We have to be careful with all the PRs that are requesting to add a logo right now. They need to be slightly rewritten to be moved to the new manifest

**Comment by mxstbr** [comment]
@el1f I will leave those to you? :pray: Also, do you have Twitter?

**Comment by el1f** [comment]
It appears like I made a mistake in #570. That branch had been rebased upon this PR so by merging #570 before #566 we ended up merging the changes in this PR too 😅

**Comment by el1f** [comment]
> @el1f I will leave those to you? 🙏 Also, do you have Twitter?

https://twitter.com/el1flem

**Comment by mxstbr** [comment]
Awesome so this is shipped! :tada:

**Pull request closed without merging**
