### PR TITLE
improvement(showcase): remove extra padding from showcase page on mobile

### PR DESCRIPTION
**Pull request by luisFilipePT**
# About
* Remove extra padding from showcase page on mobile
* Update tests related

# Screenshots

## Before
image

## After
image

Please review and reach out for changes or improvements 👐 

fix #FIX-SHOWCASE-MOBILE-PADDING
rel #616

### CODE REVIEW

**Comment by luisFilipePT** [comment]
🤔, it works on my machine 😆 
Any help on why it's failing would be cool, I believe it's snapshot related but on my side updated the snapshots and the test's run just fine. :/
image

image

**Comment by el1f** [comment]
I'm going to take a look at it after breakfast :)
Thanks for the help!

**Comment by luisFilipePT** [comment]
> I'm going to take a look at it after breakfast :)
> Thanks for the help!

No problem, happy to help 😄 
BTW - If you have time check this request to add the project I am currently working in 😊 
https://github.com/styled-components/styled-components-website/issues/617

Cheers 🎉

**Comment by luisFilipePT** [comment]
@el1f open another unrelated PR https://github.com/styled-components/styled-components-website/pull/620 and have the same tests failing :/

If you find out the reason please let me know, on my machine everything runs smoothly.

Thanks

**Comment by el1f** [comment]
Taking a look at it RN, it also seems like while fixing the padding on mobile it ended up creating a padding issue on desktop. Going to try and fix that too :)

**Comment by luisFilipePT** [comment]
> Taking a look at it RN, it also seems like while fixing the padding on mobile it ended up creating a padding issue on desktop. Going to try and fix that too :)

🤔 looking at it and can't find the issue you are referring to, if you need help jus reach out.
And if you can explain me the reason for the failing test cause would love to contribute more since I have been using styled components for a while now and I am a fan 🎉 😄

**Comment by el1f** [comment]
image

I'm referring to this. No big issue though just got to play around with the margins a little bit to find the one that's screwing up there :)
Sure! As soon as I find a fix I'll be reporting it here :D

**Pull request closed without merging**
