### PR TITLE
Sublime Text is supported for syntax highlighting

### PR DESCRIPTION
**Pull request by singingwolfboy**
The "open PR" for `styled-components` support in `babel-sublime` has been [merged for more than a year](https://github.com/babel/babel-sublime/pull/289). We should update the `styled-components` website to reflect this.

### CODE REVIEW

**Comment by philpl** [comment]
@singingwolfboy I think the last point where it was left at wasn't pretty optimal and fixes haven't been released since then? correct me if I'm wrong of course 😅  https://github.com/babel/babel-sublime/pull/289#issuecomment-283637556

cc @mxstbr

**Comment by mxstbr** [comment]
Yep, it's not released yet :cry:

**Comment by jbfm** [comment]
[Sublime-JS-Custom](https://github.com/Thom1729/Sublime-JS-Custom) is an alternative that provides `styled-components` hightlighting

**Comment by ddcast** [comment]
While reading the [tooling](https://www.styled-components.com/docs/tooling) page in the docs, I noticed the Sublime Text section needed this update and found this PR. The bot's message is a little confusing to me (and I'm not familiar with this project's flow), but it seems that this can be merged into master by a project collaborator - after first being rebased or merged with current master - (?)

Anyway, it'd be nice to see this pushed through 😉 

Great work on the site!

**Pull request closed without merging**
