### PR TITLE
Add Markdown util and convert all sections

### PR DESCRIPTION
**Pull request by philpl**
I adapted react-markings for our components: https://github.com/Thinkmill/react-markings

It should actually work better for us than converting everything to Gatsby right now, and at the same time will make the task of translating everything a lot smoother probably. Not to mention the connected refactor and redesign.

It should be relatively straightforward, apart from the manual labour that's in translating everything to markdown :(

Edit: Not building with Uglify / build task right now due to an UglifyJS bug

### CODE REVIEW

**Comment by mxstbr** [comment]
Here is a deploy of this branch: https://styled-components-docs-huxzgkpejt.now.sh

**Comment by philpl** [comment]
@mxstbr uglify is failing :) probably something minor. I’ll take a look later and fix it. Just got back from some short holidays today

**Comment by philpl** [comment]
@mxstbr Done and should be ready to merge 🚀

**Comment by mxstbr** [comment]
Let's ship this to avoid it getting hopelessly out of date?!

**Comment by mxstbr** [comment]
Let's ship this to avoid it getting hopelessly out of date?!

**Comment by mxstbr** [comment]
Awesomeeee!!!

**Pull request merged**
