### PR TITLE
Implement Google Analytics

### LINKED ISSUE #91: Add Analytics
`micro-analytics` is nice and all, but doesn't quite give us what we need and I don't have time to improve it further.

Let's switch to something else. I'd love for the stats to be public, if that's not possible because it doesn't exist let's just use Google Analytics because it's easy?

### PR DESCRIPTION
**Pull request by mxstbr**
Closes #97, closes #91

### CODE REVIEW

**Comment by harshmaur** [comment]
This kind of insertion works now with react and next?

**Comment by mxstbr** [comment]
Worked locally for me 🤷‍♂️ Any better ideas?

**Comment by harshmaur** [comment]
Did it record all the pages as well? What I know is that way of implementation will only record the landing page and subsequent page navigation wont be recorded.

**Comment by mxstbr** [comment]
Could be, I didn't test it very thorougly. PR with a better implementation very very welcome!

**Comment by harshmaur** [comment]
Hey I did that twice? 🤔 The ones you closed.

**Comment by mxstbr** [comment]
Ohhhh yeah, but those weren't working right? I took that branch and tried to fix it but gave up and did this instead because I thought it'd work that way 😅

**Comment by harshmaur** [comment]
Oh okay. Its the test which is failing, the tracking works fine.

**Comment by mxstbr** [comment]
Yeah but I mean, that's not exactly great :wink: If you can fix that I'd be a lot more happy shipping your version!

**Pull request merged**
