### PR TITLE
Upgrade Next.js

### PR DESCRIPTION
**Pull request by timneutkens**
Upgrades Next.js to the latest version.

I've tried to do the most minimal upgrade, only changes are next.config, .babelrc and package.json.

The snapshots are failing, but I guess that's because of styled-components being upgraded.

If someone else could have a look at the tests that'd be great, as I haven't touched the website before

### CODE REVIEW

**Comment by kitten** [comment]
Nice! I had a separate WIP PR for this, but it wasn't done properly, so let's start with yours and I can add on more upgrades later on.

The server-side rendering seems to be broken right now btw. Might also explain the failing image snapshots

**Comment by timneutkens** [comment]
There's a super weird issue where it renders `[object Object]` 🤔

**Comment by probablyup** [comment]
I think we might just not be babel 7 compatible https://github.com/styled-components/babel-plugin-styled-components/pull/134

**Comment by timneutkens** [comment]
@probablyup I'm pretty sure styled-components works fine for a *lot* of Next.js users on Next.js 6+ though 🤔

**Comment by probablyup** [comment]
Rolled into #293

**Comment by timneutkens** [comment]
💯 Thanks @probablyup 🙏

**Pull request closed without merging**
