### PR TITLE
Update TypeScript documentation

### LINKED ISSUE #392: TS examples need an update after 4.1
Hi There! 

It looks like the Typescript typings are broken since the upgrade to 4.1. There is an issue over at the @types repo, but I just wanted to make an issue here as well because I have the feeling that it otherwise would be overlooked. 

Please feel free to close this issue if you don't think there should be an issue here. 

The issue I'm referring to is: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30536

Thanks a lot for all the effort!!

### PR DESCRIPTION
**Pull request by Ky6uk**
Fixes #392

### CODE REVIEW

**Comment by Ky6uk** [comment]
🤔 https://styled-components-bzlvjuagup.now.sh/docs/api#typescript is broken and I have no idea why.

**Comment by fabb** [comment]
DRYed solution: https://github.com/styled-components/styled-components-website/issues/392#issuecomment-472307399

**Comment by probablyup** [comment]
@Ky6uk can you update with @fabb's version (assuming it works)?

**Comment by Ky6uk** [comment]
@probablyup Unfortunately I'm not sure the old variant is working. That was a reason why I moved to new variant.

**Comment by probablyup** [comment]
Ok np, @Igorbek do you have time to do a quick review?

**Comment by Ky6uk** [comment]
@probablyup I'm more afraid the build using `Now.sh` is showing [an error](https://styled-components-kvvgtvwxsf.now.sh/docs/api). 🤔

**Comment by fabb** [comment]
I implemented the DRYed variant in our project and it works fine there

**Comment by probablyup** [comment]
Thanks Igor! Going to ship this.

**Comment by probablyup** [comment]
Well, I will once you fix the page ;)

**Comment by Zodiase** [comment]
With this merge, the following code does not make any sense (syntax error).

image

**Comment by Ky6uk** [comment]
Yeah. Some outdated code blocks should be also updated.

**Comment by remolueoend** [comment]
Hey @Ky6uk, I know this MR is old as earth, but it seems [@Zodiase 's comment](https://github.com/styled-components/styled-components-website/pull/437#issuecomment-474515370) above is still not fixed. Should I open an MR and try to get a working example running?

**Comment by Ky6uk** [comment]
@remolueoend feel free to open any PRs in case if something wrong. Currently, I'm away from this project, but I'm sure someone else will check it.

**Comment by remolueoend** [comment]
@Ky6uk Thanks, done: https://github.com/styled-components/styled-components-website/pull/483

**Pull request merged**
