### PR TITLE
Added Patreon logo to homepage

### PR DESCRIPTION
**Pull request by JamesTheHacker**

### CODE REVIEW

**Comment by JamesJefferyUK** [comment]
Agreed I did think that myself. The bar line on the logo is the correct hight but the logo text is small. Should I modify the SVG to make the logo text bigger?

**Comment by morajabi** [comment]
Let me check their design guidelines, that might not be allowed.

**Comment by morajabi** [comment]
@mxstbr @JamesJefferyUK It's not allowed to change the logo. What the hell can we do now?! Maybe just put it somewhere that is less awkward :|

**Comment by iRoachie** [comment]
What about a negative top margin. 
screen shot 2017-12-19 at 8 02 02 am

**Comment by JamesJefferyUK** [comment]
@iRoachie the bar looks off to me (too big). Could probably get away with making the logo a little bigger than my initial modification. I'll have a play with it.

**Comment by JamesJefferyUK** [comment]
image

Better?

**Comment by iRoachie** [comment]
Look good to me

**Comment by mxstbr** [comment]
Much better, that totally works for me! 👌

**Comment by iRoachie** [comment]
@JamesJefferyUK You're going need to merge or rebase to get those changes from master, so we can accept this in.

**Comment by JamesJefferyUK** [comment]
Oops. Will sort it now.

**Comment by JamesJefferyUK** [comment]
Rebased :)

**Comment by philpl** [comment]
@JamesJefferyUK Same as the other PR :wink: this will need a quick rebase and you'll need to run `yarn integration -u`; Make sure that we merge the other PR first, as this branch will be out of date otherwise.

**Comment by morajabi** [comment]
@mxstbr Are you sure it's OK to change their trademark? They clearly said on their [branding](https://www.patreon.com/brand/guidelines) page to don't alter it.

**Comment by mxstbr** [comment]
We didn't change it? We just made it bigger?

**Comment by morajabi** [comment]
@mxstbr No look at the line, it's shortened.

**Comment by morajabi** [comment]
As I said earlier: Maybe just put it somewhere that is less awkward (maybe end of the first line?) and make it a little bit bigger to match others, not too much

**Comment by JamesJefferyUK** [comment]
I'm trying to rebase this but I've messed it up. It's going to take me some time to figure out where I've gone wrong and how to resolve.

Anyway, I've reached out the Patreon team and sent them a link to this PR. They have confirmed they've received and will respond directly here.

**Comment by jbyttow** [comment]
I spoke to our brand designer, we cannot change the logo, only the scale and placement obviously as @morajabi suggested. Thanks for checking with us @JamesJefferyUK!

**Comment by JamesJefferyUK** [comment]
No problem @jbyttow. @mxstbr will need some guidance on the best way to move forward with the logo placement?

**Comment by mxstbr** [comment]
I guess just make it a bit bigger and leave it at that 🤷‍♂️ If they don't mind it looking awkward there isn't really much we can do!

**Comment by jbyttow** [comment]
@JamesJefferyUK any movement on this :)?

**Comment by probablyup** [comment]
Closed via #250

**Pull request closed without merging**
