### PR TITLE
Ecosystem page

### PR DESCRIPTION
**Pull request by SaraVieira**
Adds ecosystem page 

Demo: https://styled-components-docs-xlylnedkic.now.sh/ecosystem

### CODE REVIEW

**Comment by SaraVieira** [comment]
🎉🤗

**Comment by SaraVieira** [comment]
Sure! Give me 30m I'm on my way to work

**Comment by morajabi** [comment]
@mxstbr I think links are a bit hard on eyes. This is nothing urgent but just to mention it for future optimizations.

Currently it looks like this: 
screen shot 2017-10-05 at 12 00 03 pm
When we were styling links we didn't think of large lists of links, I suppose :)

I did some modification (li: more margin, a: underline only on hover) and it's better on eyes:
screen shot 2017-10-05 at 12 07 20 pm

But we can do better: (maybe make font a bit lighter, smaller or something)
screen shot 2017-10-05 at 12 08 20 pm

As I said, not the focus of this PR but worth mentioning.

**Comment by mxstbr** [comment]
Yeah `li`s should have a `line-height: 1.5em;`, I'm not a big fan of removing the underlines though as that's a pretty standard convention across the web. Happy for another PR!

**Comment by morajabi** [comment]
BTW line-height with `em` is not good :) You should emit the unit.

**Comment by mxstbr** [comment]
Interesting, didn't know that!

**Comment by SaraVieira** [comment]
@mxstbr @morajabi @philpl I added some line height and some margin to all li's:

screen shot 2017-10-05 at 11 34 58


New version peeps:

https://styled-components-docs-elifqlzemz.now.sh/ecosystem

**Comment by morajabi** [comment]
I think it's now WAY better! Thanks!

**Comment by SaraVieira** [comment]
@morajabi A little breathing room makes a huge difference 🤓

**Comment by philpl** [comment]
Looks a lot better! Awesome

**Comment by SaraVieira** [comment]
@philpl Should I remove the snapshot ?

**Comment by morajabi** [comment]
@SaraVieira What do you mean? Which snapshot?

**Comment by SaraVieira** [comment]
I meant the snapshot tests , sorry

**Comment by morajabi** [comment]
I know snapshot tests, but the problem is I didn't read @philpl's msg above about the snapshots :) Yea I think you should remove the snapshot too. There are other options to test this page if it's needed.

**Comment by morajabi** [comment]
@philpl I think we should wait. Should I merge this repo into my branch on the new sidebar?

**Comment by SaraVieira** [comment]
@morajabi Removed the snapshots , I think merging into your branch would be the ideal :)

**Comment by morajabi** [comment]
@SaraVieira Will you still get the credit for commits or not?

**Comment by mxstbr** [comment]
> Shall we wait for @morajabi's customisable sidebar work first, so that we can merge it with a proper sidebar?

Let's merge as-is and then @morajabi can work on the sidebar from `master` without having to mess around with git crap and branches. It's not like the page is unusable without the sidebar :blush:

**Comment by morajabi** [comment]
@mxstbr "git crap" :)))) OK and @SaraVieira will get the credits for the contributions, I'm happy then.

**Comment by morajabi** [comment]
Let's begin

**Pull request merged**
