### PR TITLE
update snpashots

### PR DESCRIPTION
**Pull request by SaraVieira**

### CODE REVIEW

**Comment by SaraVieira** [comment]
@philpl This fixes the snpashots I forgot to push previously :(

My bad

**Comment by philpl** [comment]
Hm, I upgraded styled-components on the repo and updated the snapshots already and it seemed fine 🤔 don't think this is actually correct in this case then, right?

**Comment by SaraVieira** [comment]
Updated the base to be master :)

**Comment by philpl** [comment]
@SaraVieira I think you have to also install to get styled-components@v2.1.2, because I think the snapshots on master seem to be up to date already. 🤔 💭

**Comment by SaraVieira** [comment]
Oh, then I shall close this 😛
My bad

**Pull request closed without merging**
