### PR TITLE
Fixes issue #719. Wrap LiveEditor with <code>  to prevent browser tra…

### PR DESCRIPTION
**Pull request by shangyilim**
Fixes Issue #719 

Wrapped `LiveEditor` with `<code>`
This prevents the code to be translated by browser translations, and also to be more semantically accurate.

Added `class="notranslate"` to  `LivePreview` to prevent the code output from translating as well to be consistent with any text rendered by the code editor

### CODE REVIEW

**Comment by probablyup** [comment]
@shangyilim can you reduce your PR to only the changes described in your pull request description?

**Comment by shangyilim** [comment]
> @shangyilim can you reduce your PR to only the changes described in your pull request description?

thanks for letting me know, it was weird my tests failed so i did a snapshot update. will update as soon as possible

**Comment by shangyilim** [comment]
@probablyup, all done commits and history should be squeaky clean now

**Review by el1f — APPROVED** [review]
SGTM

**Comment by el1f** [comment]
Thanks for the help @shangyilim!!!

**Pull request merged**
